[en]
  title = "Thomas Chartron"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[fr]
  title = "Thomas Chartron"
  languageName = "French"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/fr"
